language: cpp

os:
  - linux
  - osx

env:
    - BUILD='Release'
    - BUILD='Debug'

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data
      - python-numpy
      - python-matplotlib

compiler:
    - gcc
    - clang

#Trying to test g4 via homebrew on osx. But fails when building libg4mcpl.so. To be investigated.
#before_install:
#    - set -e
#    - if [[ "$TRAVIS_OS_NAME" == "osx" -a "$BUILD" == "RELEASE" ]]; then brew update                         ; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" -a "$BUILD" == "RELEASE" ]]; then brew install homebrew/science/geant4; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" -a "$BUILD" == "RELEASE" ]]; then geant4-config --version; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" -a "$BUILD" == "RELEASE" ]]; then geant4-config --libs; fi
#    - if [[ "$TRAVIS_OS_NAME" == "osx" -a "$BUILD" == "RELEASE" ]]; then geant4-config --cflags; fi
#    - set +e

before_script:
    - set -e
    - mkdir build installdir rundir
    - cd build
    - cmake .. -DBUILD_FAT=ON -DCMAKE_BUILD_TYPE=${BUILD} -DCMAKE_INSTALL_PREFIX=../installdir/
    - set +e

script:
    - set -e
    - make VERBOSE=1 install
    - cd ../rundir
    - find ../installdir
    - ../installdir/bin/mcplexample_write myfile.mcpl
    - ../installdir/bin/mcplexample_filter myfile.mcpl.gz myfile_filtered.mcpl
    - ../installdir/bin/mcplexample_read myfile_filtered.mcpl.gz
    - ../installdir/bin/mcpltool myfile.mcpl.gz
    - ../installdir/bin/mcpltool myfile_filtered.mcpl.gz
    - ../installdir/bin/mcpltool_fat myfile_filtered.mcpl.gz
    - ../installdir/bin/mcplexample_pyread myfile.mcpl.gz
    - ../installdir/bin/pymcpltool myfile.mcpl.gz
    - ../installdir/bin/pymcpltool --stats myfile.mcpl.gz
    - ../installdir/bin/pymcpltool --stats --pdf myfile.mcpl.gz
    - set +e

notifications:
  email:
    recipients:
      - mcpl-developers@cern.ch
      - tkess@doki.dk
    on_success: change
    on_failure: always
