language: cpp

os:
  - linux
  - osx

osx_image: xcode9.2

env:
  global:
    - SHELL_SESSION_HISTORY=0
  matrix:
    - BUILD=Release
    - BUILD=Debug

addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - python-numpy
      - python-matplotlib

compiler:
    - gcc
    - clang

before_script:
    - set -e
    - mkdir build installdir rundir
    - cd build
    - cmake .. -DBUILD_FAT=ON -DCMAKE_BUILD_TYPE=${BUILD} -DCMAKE_INSTALL_PREFIX=../installdir/
    - set +e

script:
    - set -e
    - make VERBOSE=1 install
    - cd ../rundir
    - find ../installdir
    - ../installdir/bin/mcplexample_write myfile.mcpl
    - ../installdir/bin/mcplexample_filter myfile.mcpl.gz myfile_filtered.mcpl
    - ../installdir/bin/mcplexample_read myfile_filtered.mcpl.gz
    - ../installdir/bin/mcpltool myfile.mcpl.gz
    - ../installdir/bin/mcpltool myfile_filtered.mcpl.gz
    - ../installdir/bin/mcpltool_fat myfile_filtered.mcpl.gz
    - ../installdir/bin/mcplexample_pyread myfile.mcpl.gz
    - ../installdir/bin/pymcpltool myfile.mcpl.gz
    - ../installdir/bin/pymcpltool --stats myfile.mcpl.gz
    - python -c 'import matplotlib' 2>/dev/null || pip install matplotlib
    - ../installdir/bin/pymcpltool --stats --pdf myfile.mcpl.gz
    - set +e

notifications:
  email:
    recipients:
      - mcpl-developers@cern.ch
    on_success: change
    on_failure: always
